workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    # machineType: n1-standard-32
    # acceleratorType: NVIDIA_TESLA_V100
    # machineType: a2-ultragpu-1g
    # acceleratorType: NVIDIA_A100_80GB
    # acceleratorCount: 4
  replicaCount: 1
  containerSpec:
    imageUri: 'gcr.io/kommunityproject/pytorch-train:v1.0.11'     
    env:
      - name: GCS_BUCKET_NAME
        value: gs://jp-ai
      - name: BRANCH_NAME
        value: feat/ada-fixed4
      - name: GITHUB_REPO
        value: https://github.com/johndpope/imf.git
